name: Grade Submissions

on:
  workflow_dispatch:
    inputs:
      gists_path:
        description: "Path to gists list file (optional if using sheet)"
        default: ""
        required: false
      sheet_id:
        description: "Google Sheet ID to read gist URLs (optional; defaults to secret)"
        required: false
      sheet_tab:
        description: "Worksheet name to read (optional; defaults to first sheet)"
        required: false
      result_tab:
        description: "Worksheet name to write results (optional; defaults to 'results' or first sheet)"
        default: "results"
        required: false

jobs:
  grade:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Install system packages (fonts)
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk
          echo "MPLBACKEND=Agg" >> $GITHUB_ENV

      - name: Install Python deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Run grading
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          RESULT_TAB: ${{ github.event.inputs.result_tab }}
        run: |
          SHEET_ID_INPUT="${{ github.event.inputs.sheet_id }}"
          # 入力がなければ Secrets（ある場合）を使用
          SHEET_ID=${SHEET_ID_INPUT:-${{ secrets.GOOGLE_SHEET_ID }}}

          echo "Using SHEET_ID=${SHEET_ID}"
          # ← 書き込み側(report.py)が参照する環境変数をここで上書き
          export GOOGLE_SHEET_ID="${SHEET_ID}"

          python run.py \
            --gists "${{ github.event.inputs.gists_path }}" \
            --sheet-id "${SHEET_ID}" \
            --sheet-tab "${{ github.event.inputs.sheet_tab }}" \
            --out .out --push-to-sheets

      - name: Upload artifacts (logs & images)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: grading-artifacts
          path: .out/**            # 再帰的に収集
          if-no-files-found: error # 無ければ失敗にして気づける

      - name: Job summary
        if: always()
        run: |
          echo "### Grading finished" >> $GITHUB_STEP_SUMMARY
          if [ -f .out/results.csv ]; then
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "Top of results.csv:" >> $GITHUB_STEP_SUMMARY
            head -n 10 .out/results.csv | sed 's/^/    /' >> $GITHUB_STEP_SUMMARY
          fi
